# Generated by Django 4.2.5 on 2023-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_word',
            field=models.CharField(default='P7EZ', max_length=255, verbose_name='Кодовое слово'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('1', 'Дошкольное'), ('2', 'Начальное общее — 1—4 классы'), ('3', 'Основное общее — 5—9 классы'), ('4', 'Среднее общее — 10—11 классы'), ('5', 'Среднее профисеональное'), ('6', 'Высшее I степени — бакалавриат'), ('7', 'Высшее II степени — специалитет, магистратура'), ('8', 'Высшее III степени — подготовка кадров высшей квалификации')], max_length=255, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'М'), ('Woman', 'Ж')], max_length=255, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='Users', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='my_story',
            field=models.TextField(null=True, verbose_name='Об авторе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='Область(Только для россиян)'),
        ),
    ]
