# Generated by Django 4.2.5 on 2023-10-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_code_word_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_word',
            field=models.CharField(default='0DRZ', max_length=255, verbose_name='Кодовое слово'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Users/no-image.svg', null=True, upload_to='Users', verbose_name='Фото'),
        ),
    ]
